"""
train_multimodel_v2.py
------------------------
Trains and compares 5 correction approaches against the real dataset.csv:
  1. Dense_v2            -- 20-input Dense MLP (K-type window + derivative window)
  2. TCN_Hadamard_v2      -- dilated causal Conv1D branch + Hadamard-transform branch
  3. Hybrid_Physics_v2    -- fitted first-order lag physics model + residual Dense net
  4. RandomForest         -- sklearn RF exported to C via emlearn
  5. Kalman               -- hand-written constant-velocity Kalman filter (kalman_filter_v2.h)

CLI: python train_multimodel_v2.py --csv dataset.csv

Known environment quirks handled here (discovered while building this script):
  - TF 2.21 defaults to Keras 3, but tensorflow-model-optimization's
    quantize_model() targets legacy Keras 2. TF_USE_LEGACY_KERAS=1 (set before
    importing tensorflow) makes tf.keras bind to the tf_keras compat package,
    which resolves this for plain Dense models.
  - tfmot's default quantize registry does NOT support Conv1D layers at all,
    independent of the Keras-3 issue above. QAT for TCN_Hadamard_v2 will
    therefore fail -- this is caught, logged clearly, and skipped; only
    float32 + ptq_int8 are produced for that model.
  - TFLite's int8 calibrator has a bug with multi-input models when the
    representative_dataset yields positional lists -- it must yield a dict
    keyed by the Keras Input layer's `name`.
  - emlearn's default dtype='int16_t' truncates raw feature/threshold values
    to integers, destroying sub-degree precision for this data. We use
    dtype='float' instead so on-device RF behavior matches the sklearn
    predictions used for the comparison table.
"""

import os
os.environ['TF_USE_LEGACY_KERAS'] = '1'

import argparse
import re
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import (
    Input, Dense, Conv1D, GlobalAveragePooling1D, Add, Concatenate, ReLU
)
from scipy.linalg import hadamard
from scipy.optimize import minimize_scalar

# Fixed seed -- without this, Dense_v2/TCN_Hadamard_v2/Hybrid_Physics_v2's
# residual net get different random weight initialization and minibatch
# shuffling on every run, which was observed to flip the cross-model ranking
# entirely between runs (not a real difference between approaches, just
# training noise). Fix it so results are reproducible and citable.
SEED = 42
np.random.seed(SEED)
tf.random.set_seed(SEED)
from sklearn.ensemble import RandomForestRegressor
import emlearn
import tensorflow_model_optimization as tfmot

import features_v2 as fv2

# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------
parser = argparse.ArgumentParser()
parser.add_argument('--csv', default='dataset.csv')
args = parser.parse_args()

QAT_EPOCHS = 10
RESULTS = []  # rows for model_comparison_v2.csv


# ---------------------------------------------------------------------------
# Shared helpers
# ---------------------------------------------------------------------------
def mae_rmse(y_true_c, y_pred_c):
    err = np.asarray(y_pred_c) - np.asarray(y_true_c)
    mae = float(np.mean(np.abs(err)))
    rmse = float(np.sqrt(np.mean(err ** 2)))
    return mae, rmse


def write_header(tflite_bytes, out_path, array_name):
    hex_parts = []
    for i, b in enumerate(tflite_bytes):
        if i % 12 == 0:
            hex_parts.append("\n  ")
        hex_parts.append(f"0x{b:02x}, ")
    guard = os.path.splitext(os.path.basename(out_path))[0].upper() + '_H'
    header = f"""\
// Auto-generated by train_multimodel_v2.py — do not edit manually.
#ifndef {guard}
#define {guard}

alignas(8) const unsigned char {array_name}[] = {{{''.join(hex_parts)}
}};
const unsigned int {array_name}_len = {len(tflite_bytes)};

#endif // {guard}
"""
    with open(out_path, 'w') as f:
        f.write(header)
    print(f"  Wrote {out_path} ({len(tflite_bytes)} bytes)")


def record_result(model_name, precision, tflite_bytes, pred_c, pt_true_c, param_count):
    mae, rmse = mae_rmse(pt_true_c, pred_c)
    RESULTS.append(dict(
        model_name=model_name, precision=precision,
        val_MAE_C=round(mae, 4), val_RMSE_C=round(rmse, 4),
        size_bytes=len(tflite_bytes), param_count=param_count
    ))
    print(f"  {model_name} [{precision}] -- val MAE: {mae:.4f} C, RMSE: {rmse:.4f} C, size: {len(tflite_bytes)} bytes")


def convert_float32(model):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    return converter.convert()


def convert_ptq_int8(model, rep_data_fn):
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = rep_data_fn
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def convert_qat_int8(model, X_train_qat, y_train_qat, rep_data_fn, custom_objects=None, epochs=QAT_EPOCHS):
    if custom_objects:
        with tfmot.quantization.keras.quantize_scope(custom_objects):
            qat_model = tfmot.quantization.keras.quantize_model(model)
    else:
        qat_model = tfmot.quantization.keras.quantize_model(model)
    qat_model.compile(optimizer='adam', loss='mse')
    qat_model.fit(X_train_qat, y_train_qat, epochs=epochs, batch_size=64, verbose=1)

    converter = tf.lite.TFLiteConverter.from_keras_model(qat_model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = rep_data_fn
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8
    return converter.convert()


def run_tflite_single_input(tflite_bytes, X_val, is_int8=True):
    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()
    in_detail = interpreter.get_input_details()[0]
    out_detail = interpreter.get_output_details()[0]

    n = X_val.shape[0]
    preds = np.zeros(n, dtype=np.float32)
    for i in range(n):
        sample = X_val[i:i + 1]
        if is_int8:
            scale, zp = in_detail['quantization']
            sample_q = np.round(sample / scale + zp).astype(in_detail['dtype'])
            interpreter.set_tensor(in_detail['index'], sample_q)
        else:
            interpreter.set_tensor(in_detail['index'], sample.astype(in_detail['dtype']))
        interpreter.invoke()
        out = interpreter.get_tensor(out_detail['index'])
        if is_int8:
            scale, zp = out_detail['quantization']
            out = (out.astype(np.float32) - zp) * scale
        preds[i] = out.flatten()[0]
    return preds


def run_tflite_multi_input(tflite_bytes, X_seq_val, X_had_val, is_int8=True):
    interpreter = tf.lite.Interpreter(model_content=tflite_bytes)
    interpreter.allocate_tensors()
    input_details = interpreter.get_input_details()
    out_detail = interpreter.get_output_details()[0]

    # Identify the 3D (sequence) vs 2D (Hadamard) input tensors by shape rank
    # rather than by name -- robust to any name-mangling the converter applies.
    seq_detail = next(d for d in input_details if len(d['shape']) == 3)
    had_detail = next(d for d in input_details if len(d['shape']) == 2)

    n = X_seq_val.shape[0]
    preds = np.zeros(n, dtype=np.float32)
    for i in range(n):
        seq_sample = X_seq_val[i:i + 1]
        had_sample = X_had_val[i:i + 1]
        if is_int8:
            s_scale, s_zp = seq_detail['quantization']
            interpreter.set_tensor(seq_detail['index'], np.round(seq_sample / s_scale + s_zp).astype(seq_detail['dtype']))
            h_scale, h_zp = had_detail['quantization']
            interpreter.set_tensor(had_detail['index'], np.round(had_sample / h_scale + h_zp).astype(had_detail['dtype']))
        else:
            interpreter.set_tensor(seq_detail['index'], seq_sample.astype(seq_detail['dtype']))
            interpreter.set_tensor(had_detail['index'], had_sample.astype(had_detail['dtype']))
        interpreter.invoke()
        out = interpreter.get_tensor(out_detail['index'])
        if is_int8:
            o_scale, o_zp = out_detail['quantization']
            out = (out.astype(np.float32) - o_zp) * o_scale
        preds[i] = out.flatten()[0]
    return preds


# ---------------------------------------------------------------------------
# Step 2.1 -- Load and prepare data
# ---------------------------------------------------------------------------
print("=" * 70)
print("STEP 2.1 -- Load and prepare data")
print("=" * 70)

df = fv2.load_dataset(args.csv)

ts_diff_ms = df['Timestamp_ms'].diff().dropna()
DT_SECONDS = float(ts_diff_ms.median()) / 1000.0
print(f"DT_SECONDS (measured median sampling interval): {DT_SECONDS}")

k_raw = df['K_Type_Temp_C'].values.astype(np.float32)
pt_raw = df['PT100_Temp_C'].values.astype(np.float32)

dk_raw = fv2.compute_derivative(k_raw, DT_SECONDS)
D_MIN, D_MAX = fv2.get_derivative_bounds(dk_raw)
print(f"DERIVATIVE BOUNDS (hardcode into firmware): D_MIN={D_MIN}, D_MAX={D_MAX}")

k_scaled = fv2.scale_temp(k_raw)
dk_scaled = fv2.scale_derivative(dk_raw, D_MIN, D_MAX)
pt_scaled = fv2.scale_temp(pt_raw)

X_flat, X_seq, y = fv2.build_windows(k_scaled, dk_scaled, pt_scaled, lookback=fv2.LOOKBACK)
X_flat_raw, _, _ = fv2.build_windows(k_raw, dk_raw, pt_raw, lookback=fv2.LOOKBACK)

# Hadamard branch input: most recent 8 of the 10 K-type-only scaled readings per window
X_had = X_seq[:, -fv2.HADAMARD_WINDOW:, 0]

X_flat_train, X_flat_val, y_train, y_val = fv2.train_val_split_timeordered(X_flat, y)
n_train = len(X_flat_train)
N = len(X_flat)

X_seq_train, X_seq_val = X_seq[:n_train], X_seq[n_train:]
X_had_train, X_had_val = X_had[:n_train], X_had[n_train:]
X_flat_raw_train, X_flat_raw_val = X_flat_raw[:n_train], X_flat_raw[n_train:]

# Single-step-aligned raw arrays K[n], K[n-1], PT100[n] for the physics/RF steps,
# aligned with the same window targets as y (target at original index i+LOOKBACK).
idx = np.arange(fv2.LOOKBACK, fv2.LOOKBACK + N)
k_vals_all = k_raw[idx]
k_prev_vals_all = k_raw[idx - 1]
pt_vals_all = pt_raw[idx]

k_vals_train, k_vals_val = k_vals_all[:n_train], k_vals_all[n_train:]
k_prev_vals_train, k_prev_vals_val = k_prev_vals_all[:n_train], k_prev_vals_all[n_train:]
pt_vals_train, pt_vals_val = pt_vals_all[:n_train], pt_vals_all[n_train:]

print(f"Data split: {n_train} train windows, {N - n_train} val windows")


# ---------------------------------------------------------------------------
# Step 2.2 -- Dense_v2
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.2 -- Dense_v2")
print("=" * 70)

dense_v2_model = Sequential([
    Input(shape=(fv2.LOOKBACK * 2,)),
    Dense(16, activation='relu'),
    Dense(8, activation='relu'),
    Dense(1)
], name='dense_v2_model')
dense_v2_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
dense_v2_model.summary()

dense_v2_model.fit(
    X_flat_train, y_train,
    epochs=30, batch_size=64,
    validation_data=(X_flat_val, y_val),
    verbose=1
)


# ---------------------------------------------------------------------------
# Step 2.3 -- TCN_Hadamard_v2
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.3 -- TCN_Hadamard_v2")
print("=" * 70)


class HadamardTransform(tf.keras.layers.Layer):
    """Fixed Hadamard transform with a trainable per-coefficient soft-threshold."""

    def __init__(self, size=8, **kwargs):
        super().__init__(**kwargs)
        self.size = size
        H = hadamard(size) / np.sqrt(size)
        self.H = tf.constant(H, dtype=tf.float32)

    def build(self, input_shape):
        self.theta = self.add_weight(
            name='theta', shape=(self.size,),
            initializer=tf.keras.initializers.Constant(0.05), trainable=True
        )
        super().build(input_shape)

    def call(self, x):
        coeffs = tf.matmul(x, self.H)
        # Soft-threshold expressed purely via RELU and subtraction -- no
        # SIGN, ABS, WHERE, or SELECT op anywhere in this formula.
        # sign(x)*relu(|x|-theta) == relu(x-theta) - relu(-x-theta)
        # (identical for x>theta, x<-theta, and |x|<=theta -- verify by cases).
        # A prior version used tf.sign()/tf.abs(), and even a tf.where()-based
        # substitute for tf.sign() alone still failed on-device: the TFLite
        # converter's graph optimizer can canonicalize a "where(x>=0, 1, -1)"
        # pattern back into a SIGN op during conversion, and this ESP32
        # build's AllOpsResolver does not have SIGN registered, so
        # AllocateTensors() failed at runtime regardless of the Python source
        # no longer calling tf.sign() directly. This RELU-only formulation
        # cannot be fused back into SIGN.
        thresholded = tf.nn.relu(coeffs - self.theta) - tf.nn.relu(-coeffs - self.theta)
        return tf.matmul(thresholded, self.H)

    def get_config(self):
        config = super().get_config()
        config.update({'size': self.size})
        return config


tcn_input = Input(shape=(fv2.LOOKBACK, 2), name='tcn_input')
c1 = Conv1D(8, 3, dilation_rate=1, padding='causal', activation='relu', name='tcn_conv1')(tcn_input)
c2 = Conv1D(8, 3, dilation_rate=2, padding='causal', activation='relu', name='tcn_conv2')(c1)
proj = Conv1D(8, 1, padding='same', name='tcn_residual_proj')(tcn_input)
added = Add(name='tcn_residual_add')([proj, c2])
relu_out = ReLU(name='tcn_residual_relu')(added)
pooled = GlobalAveragePooling1D(name='tcn_pool')(relu_out)

hadamard_input = Input(shape=(fv2.HADAMARD_WINDOW,), name='hadamard_input')
had_out = HadamardTransform(size=fv2.HADAMARD_WINDOW, name='hadamard_transform')(hadamard_input)

concat = Concatenate(name='tcn_hadamard_concat')([pooled, had_out])
d1 = Dense(8, activation='relu', name='tcn_hadamard_dense')(concat)
tcn_out = Dense(1, name='tcn_hadamard_out')(d1)

tcn_hadamard_v2_model = Model(inputs=[tcn_input, hadamard_input], outputs=tcn_out, name='tcn_hadamard_v2_model')
tcn_hadamard_v2_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
tcn_hadamard_v2_model.summary()
print(f"TCN_Hadamard_v2 total params: {tcn_hadamard_v2_model.count_params()}")

tcn_hadamard_v2_model.fit(
    [X_seq_train, X_had_train], y_train,
    epochs=30, batch_size=64,
    validation_data=([X_seq_val, X_had_val], y_val),
    verbose=1
)


# ---------------------------------------------------------------------------
# Step 2.4 -- Hybrid_Physics_v2
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.4 -- Hybrid_Physics_v2")
print("=" * 70)


def lag_model_mse(tau, rate_vals, k_vals, pt_vals):
    physics_est = k_vals + tau * rate_vals
    return np.mean((physics_est - pt_vals) ** 2)


def causal_moving_average(x, window):
    """Past-only moving average (no future lookahead) -- realizable on the firmware."""
    result = np.zeros_like(x)
    for i in range(len(x)):
        start = max(0, i - window + 1)
        result[i] = np.mean(x[start:i + 1])
    return result


# --- Fit A: tau against the raw single-step derivative (original approach) ---
raw_rate_train = (k_vals_train - k_prev_vals_train) / DT_SECONDS
raw_rate_val = (k_vals_val - k_prev_vals_val) / DT_SECONDS
result_raw = minimize_scalar(
    lambda tau: lag_model_mse(tau, raw_rate_train, k_vals_train, pt_vals_train),
    bounds=(0.0, 20.0), method='bounded'
)
tau_hat_raw = float(result_raw.x)
physics_raw_val = k_vals_val + tau_hat_raw * raw_rate_val
mae_raw, rmse_raw = mae_rmse(pt_vals_val, physics_raw_val)
print(f"TAU_HAT fit on raw single-step derivative: {tau_hat_raw} (val MAE {mae_raw:.4f} C, RMSE {rmse_raw:.4f} C)")

# --- Fit B (code-review experiment): tau against a smoothed derivative, to test
# whether single-step derivative noise -- rather than a missing bias/intercept
# term -- was suppressing a meaningful tau. ---
SMOOTH_WINDOW = 3
dk_smoothed_raw = causal_moving_average(dk_raw, SMOOTH_WINDOW)
dk_smoothed_all = dk_smoothed_raw[idx]
dk_smoothed_train, dk_smoothed_val = dk_smoothed_all[:n_train], dk_smoothed_all[n_train:]

result_smoothed = minimize_scalar(
    lambda tau: lag_model_mse(tau, dk_smoothed_train, k_vals_train, pt_vals_train),
    bounds=(0.0, 20.0), method='bounded'
)
tau_hat_smoothed = float(result_smoothed.x)
physics_smoothed_val = k_vals_val + tau_hat_smoothed * dk_smoothed_val
mae_smoothed, rmse_smoothed = mae_rmse(pt_vals_val, physics_smoothed_val)
print(f"TAU_HAT fit on {SMOOTH_WINDOW}-sample causal-smoothed derivative: {tau_hat_smoothed} "
      f"(val MAE {mae_smoothed:.4f} C, RMSE {rmse_smoothed:.4f} C)")

# --- Diagnostic: is the K-vs-PT100 gap dominated by a roughly constant sensor
# offset (which this intercept-free physics formula structurally cannot
# capture, regardless of derivative smoothing) rather than a rate-dependent
# thermal lag? ---
mae_raw_k, rmse_raw_k = mae_rmse(pt_vals_val, k_vals_val)
print(f"DIAGNOSTIC -- raw uncorrected K-type vs PT100 (no correction at all): "
      f"MAE {mae_raw_k:.4f} C, RMSE {rmse_raw_k:.4f} C")
print("  If this is close to both TAU_HAT fits above, the K-vs-PT100 gap is likely "
      "offset-dominated, not lag-dominated -- physics_correction = k + tau*rate has no "
      "bias/intercept term, so it cannot capture a constant offset no matter how the "
      "derivative is estimated. In that case the residual Dense net is doing nearly all "
      "of Hybrid_Physics_v2's correction, and TAU_HAT being tiny reflects a real property "
      "of this sensor pair, not a bug in the fit.")

# Pick whichever fit generalizes better; raw wins ties (keeps PLAN.md's literal
# formula unless smoothing is concretely better on held-out validation data).
if rmse_smoothed < rmse_raw:
    TAU_HAT = tau_hat_smoothed
    USE_SMOOTHED_DERIVATIVE_FOR_PHYSICS = True
    physics_correction_all = k_vals_all + TAU_HAT * dk_smoothed_all
    print(f"Using SMOOTHED-derivative TAU_HAT for Hybrid_Physics_v2 (better val RMSE): {TAU_HAT}")
    print(f"NOTE: firmware's Hybrid physics term must feed a {SMOOTH_WINDOW}-sample causal "
          f"moving average of the derivative, not the raw single-step diff (Dense_v2 and "
          f"TCN_Hadamard_v2 inputs are unaffected -- they still use the raw derivative).")
else:
    TAU_HAT = tau_hat_raw
    USE_SMOOTHED_DERIVATIVE_FOR_PHYSICS = False
    physics_correction_all = k_vals_all + TAU_HAT * ((k_vals_all - k_prev_vals_all) / DT_SECONDS)
    print(f"Using RAW-derivative TAU_HAT for Hybrid_Physics_v2 (smoothing did not improve val RMSE): {TAU_HAT}")

print(f"PHYSICS TAU_HAT (hardcode into firmware as TAU_HAT): {TAU_HAT}")

residual_target_all = pt_vals_all - physics_correction_all

residual_target_train = residual_target_all[:n_train]
residual_target_val = residual_target_all[n_train:]
physics_correction_val = physics_correction_all[n_train:]

R_MAX = float(np.max(np.abs(residual_target_train)))
print(f"RESIDUAL_SCALE (hardcode into firmware): {R_MAX}")

residual_scaled_train = (residual_target_train / R_MAX).reshape(-1, 1).astype(np.float32)
residual_scaled_val = (residual_target_val / R_MAX).reshape(-1, 1).astype(np.float32)

hybrid_v2_model = Sequential([
    Input(shape=(fv2.LOOKBACK * 2,)),
    Dense(8, activation='relu'),
    Dense(1)
], name='hybrid_v2_residual_model')
hybrid_v2_model.compile(optimizer='adam', loss='mse', metrics=['mae'])
hybrid_v2_model.summary()

hybrid_v2_model.fit(
    X_flat_train, residual_scaled_train,
    epochs=30, batch_size=64,
    validation_data=(X_flat_val, residual_scaled_val),
    verbose=1
)

physics_only_mae, physics_only_rmse = mae_rmse(pt_vals_val, physics_correction_val)
print(f"  (reference: physics-only baseline before residual net -- MAE: {physics_only_mae:.4f} C, RMSE: {physics_only_rmse:.4f} C)")


# ---------------------------------------------------------------------------
# Step 2.5 -- Quantization exports: Dense_v2, TCN_Hadamard_v2
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.5 -- Quantization exports (Dense_v2, TCN_Hadamard_v2)")
print("=" * 70)

# --- Dense_v2 ---
print("\n-- Dense_v2 exports --")


def dense_rep_data():
    for i in range(min(200, len(X_flat_train))):
        yield [X_flat_train[i:i + 1].astype(np.float32)]


dense_float32 = convert_float32(dense_v2_model)
write_header(dense_float32, 'model_data_dense_v2_float32.h', 'model_data_dense_v2_float32')
pred_c = fv2.unscale_temp(dense_v2_model.predict(X_flat_val, verbose=0).flatten())
record_result('Dense_v2', 'float32', dense_float32, pred_c, pt_vals_val, dense_v2_model.count_params())

dense_ptq = convert_ptq_int8(dense_v2_model, dense_rep_data)
write_header(dense_ptq, 'model_data_dense_v2_ptq_int8.h', 'model_data_dense_v2_ptq_int8')
pred_c_ptq = fv2.unscale_temp(run_tflite_single_input(dense_ptq, X_flat_val, is_int8=True))
record_result('Dense_v2', 'ptq_int8', dense_ptq, pred_c_ptq, pt_vals_val, dense_v2_model.count_params())

try:
    dense_qat = convert_qat_int8(dense_v2_model, X_flat_train, y_train, dense_rep_data)
    write_header(dense_qat, 'model_data_dense_v2_qat_int8.h', 'model_data_dense_v2_qat_int8')
    pred_c_qat = fv2.unscale_temp(run_tflite_single_input(dense_qat, X_flat_val, is_int8=True))
    record_result('Dense_v2', 'qat_int8', dense_qat, pred_c_qat, pt_vals_val, dense_v2_model.count_params())
    print("QAT succeeded for Dense_v2 via TF_USE_LEGACY_KERAS shim")
except Exception as e:
    print(f"QAT skipped for Dense_v2: {e} -- TF_USE_LEGACY_KERAS shim did not resolve compatibility; "
          f"continuing with float32 + PTQ int8 only")

# --- TCN_Hadamard_v2 ---
print("\n-- TCN_Hadamard_v2 exports --")


def tcn_rep_data():
    for i in range(min(200, len(X_seq_train))):
        yield {
            'tcn_input': X_seq_train[i:i + 1].astype(np.float32),
            'hadamard_input': X_had_train[i:i + 1].astype(np.float32),
        }


tcn_float32 = convert_float32(tcn_hadamard_v2_model)
write_header(tcn_float32, 'model_data_tcn_hadamard_v2_float32.h', 'model_data_tcn_hadamard_v2_float32')
pred_c = fv2.unscale_temp(tcn_hadamard_v2_model.predict([X_seq_val, X_had_val], verbose=0).flatten())
record_result('TCN_Hadamard_v2', 'float32', tcn_float32, pred_c, pt_vals_val, tcn_hadamard_v2_model.count_params())

tcn_ptq = convert_ptq_int8(tcn_hadamard_v2_model, tcn_rep_data)
write_header(tcn_ptq, 'model_data_tcn_hadamard_v2_ptq_int8.h', 'model_data_tcn_hadamard_v2_ptq_int8')
pred_c_ptq = fv2.unscale_temp(run_tflite_multi_input(tcn_ptq, X_seq_val, X_had_val, is_int8=True))
record_result('TCN_Hadamard_v2', 'ptq_int8', tcn_ptq, pred_c_ptq, pt_vals_val, tcn_hadamard_v2_model.count_params())

try:
    tcn_qat = convert_qat_int8(
        tcn_hadamard_v2_model, [X_seq_train, X_had_train], y_train, tcn_rep_data,
        custom_objects={'HadamardTransform': HadamardTransform}
    )
    write_header(tcn_qat, 'model_data_tcn_hadamard_v2_qat_int8.h', 'model_data_tcn_hadamard_v2_qat_int8')
    pred_c_qat = fv2.unscale_temp(run_tflite_multi_input(tcn_qat, X_seq_val, X_had_val, is_int8=True))
    record_result('TCN_Hadamard_v2', 'qat_int8', tcn_qat, pred_c_qat, pt_vals_val, tcn_hadamard_v2_model.count_params())
    print("QAT succeeded for TCN_Hadamard_v2 via TF_USE_LEGACY_KERAS shim")
except Exception as e:
    print(f"QAT skipped for TCN_Hadamard_v2: {e} -- tensorflow-model-optimization's default quantize "
          f"registry does not support Conv1D layers (a hard library limitation, not a Keras-3 issue); "
          f"continuing with float32 + PTQ int8 only")


# ---------------------------------------------------------------------------
# Step 2.6 -- Random Forest via emlearn
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.6 -- Random Forest via emlearn")
print("=" * 70)

y_raw_train = pt_vals_train
y_raw_val = pt_vals_val

# n_estimators=8, max_depth=6 (down from 15/8 in an earlier version) -- the
# earlier forest produced an ~822KB header, which risks the ESP32 flash
# partition and Arduino compile time. Fewer/shallower trees trade a small
# amount of accuracy for a substantially smaller artifact.
rf = RandomForestRegressor(n_estimators=8, max_depth=6, random_state=42)
rf.fit(X_flat_raw_train, y_raw_train)
rf_pred_val = rf.predict(X_flat_raw_val)
rf_mae, rf_rmse = mae_rmse(y_raw_val, rf_pred_val)
print(f"Random Forest (sklearn, Python-side) -- val MAE: {rf_mae:.4f} C, RMSE: {rf_rmse:.4f} C")

# dtype='float' (NOT emlearn's default 'int16_t') -- the default truncates every
# raw feature/threshold to an integer, which would collapse all sub-degree
# precision in our raw C/derivative inputs and make on-device behavior diverge
# sharply from the sklearn numbers above. float keeps them consistent.
cmodel = emlearn.convert(rf, method='inline', dtype='float')
cmodel.save(file='rf_model_v2.h', name='rf_model')
rf_size_bytes = os.path.getsize('rf_model_v2.h')
print(f"  Wrote rf_model_v2.h ({rf_size_bytes} bytes)")

# Re-verify the generated function name/signature from the actual file rather
# than assuming it -- don't hand the firmware a call site based on a guess.
with open('rf_model_v2.h', 'r') as f:
    rf_header_text = f.read()
rf_predict_match = re.search(r'^\s*(?:float|int32_t)\s+\w*_predict\s*\([^)]*\)\s*\{', rf_header_text, re.MULTILINE)
if rf_predict_match:
    print(f"  Verified generated predict function: {rf_predict_match.group(0).strip().rstrip('{').strip()}")
else:
    print("  [WARNING] Could not locate a *_predict(...) function in rf_model_v2.h -- "
          "inspect the file manually before writing the firmware call site.")

RESULTS.append(dict(
    model_name='RandomForest', precision='float',
    val_MAE_C=round(rf_mae, 4), val_RMSE_C=round(rf_rmse, 4),
    size_bytes=rf_size_bytes, param_count=0
))


# ---------------------------------------------------------------------------
# Step 2.7 -- Hybrid_Physics_v2 quantization exports
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.7 -- Hybrid_Physics_v2 quantization exports")
print("=" * 70)
print("  NOTE: firmware uses the float32 variant of this model by default -- the physics")
print("  term's derivative math needs float precision. PTQ/QAT variants are produced here")
print("  only for comparison-table completeness.")


def hybrid_rep_data():
    for i in range(min(200, len(X_flat_train))):
        yield [X_flat_train[i:i + 1].astype(np.float32)]


hybrid_float32 = convert_float32(hybrid_v2_model)
write_header(hybrid_float32, 'model_data_hybrid_v2_float32.h', 'model_data_hybrid_v2_float32')
residual_pred_val_f32 = hybrid_v2_model.predict(X_flat_val, verbose=0).flatten() * R_MAX
pred_c = physics_correction_val + residual_pred_val_f32
record_result('Hybrid_Physics_v2', 'float32', hybrid_float32, pred_c, pt_vals_val, hybrid_v2_model.count_params())

hybrid_ptq = convert_ptq_int8(hybrid_v2_model, hybrid_rep_data)
write_header(hybrid_ptq, 'model_data_hybrid_v2_ptq_int8.h', 'model_data_hybrid_v2_ptq_int8')
residual_pred_val_ptq = run_tflite_single_input(hybrid_ptq, X_flat_val, is_int8=True) * R_MAX
pred_c_ptq = physics_correction_val + residual_pred_val_ptq
record_result('Hybrid_Physics_v2', 'ptq_int8', hybrid_ptq, pred_c_ptq, pt_vals_val, hybrid_v2_model.count_params())

try:
    hybrid_qat = convert_qat_int8(hybrid_v2_model, X_flat_train, residual_scaled_train, hybrid_rep_data)
    write_header(hybrid_qat, 'model_data_hybrid_v2_qat_int8.h', 'model_data_hybrid_v2_qat_int8')
    residual_pred_val_qat = run_tflite_single_input(hybrid_qat, X_flat_val, is_int8=True) * R_MAX
    pred_c_qat = physics_correction_val + residual_pred_val_qat
    record_result('Hybrid_Physics_v2', 'qat_int8', hybrid_qat, pred_c_qat, pt_vals_val, hybrid_v2_model.count_params())
    print("QAT succeeded for Hybrid_Physics_v2 via TF_USE_LEGACY_KERAS shim")
except Exception as e:
    print(f"QAT skipped for Hybrid_Physics_v2: {e} -- continuing with float32 + PTQ int8 only")


# ---------------------------------------------------------------------------
# Step 2.8 -- Kalman filter (Python mirror of kalman_filter_v2.h) + comparison CSV
# ---------------------------------------------------------------------------
print("\n" + "=" * 70)
print("STEP 2.8 -- Kalman filter (Python mirror) + model_comparison_v2.csv")
print("=" * 70)

KALMAN_Q_TEMP = 0.001
KALMAN_Q_VEL = 0.0001
KALMAN_R_MEAS = 0.25


def kalman_filter_python(measurements, dt):
    """Mirrors the exact predict/update equations in kalman_filter_v2.h."""
    n = len(measurements)
    preds = np.zeros(n)
    x = measurements[0]
    v = 0.0
    p00, p01, p10, p11 = 1.0, 0.0, 0.0, 1.0
    preds[0] = x
    for i in range(1, n):
        z = measurements[i]
        x_pred = x + v * dt
        v_pred = v

        p00_pred = p00 + dt * (p10 + p01) + dt * dt * p11 + KALMAN_Q_TEMP
        p01_pred = p01 + dt * p11
        p10_pred = p10 + dt * p11
        p11_pred = p11 + KALMAN_Q_VEL

        innovation = z - x_pred
        S = p00_pred + KALMAN_R_MEAS
        k0 = p00_pred / S
        k1 = p10_pred / S

        x = x_pred + k0 * innovation
        v = v_pred + k1 * innovation

        p00 = (1 - k0) * p00_pred
        p01 = (1 - k0) * p01_pred
        p10 = p10_pred - k1 * p00_pred
        p11 = p11_pred - k1 * p01_pred

        preds[i] = x
    return preds


# Run continuously over the FULL raw K-type series (matching real firmware
# behavior -- the filter is never reset), then evaluate only on the val
# window's target indices so the filter has already "warmed up" on train data.
kalman_preds_full = kalman_filter_python(k_raw, DT_SECONDS)
kalman_preds_at_targets = kalman_preds_full[idx]
kalman_pred_val = kalman_preds_at_targets[n_train:]
kalman_mae, kalman_rmse = mae_rmse(pt_vals_val, kalman_pred_val)
print(f"Kalman filter (Python mirror) -- val MAE: {kalman_mae:.4f} C, RMSE: {kalman_rmse:.4f} C")

KALMAN_SIZE_BYTES_ESTIMATE = 400  # a few hundred bytes of code, no learned parameters
RESULTS.append(dict(
    # NOTE: precision label is 'analytic', not 'n/a' -- pandas' read_csv treats
    # the literal string 'n/a' as a NaN sentinel by default, which silently
    # breaks any downstream string concatenation/plotting on this column.
    model_name='Kalman', precision='analytic',
    val_MAE_C=round(kalman_mae, 4), val_RMSE_C=round(kalman_rmse, 4),
    size_bytes=KALMAN_SIZE_BYTES_ESTIMATE, param_count=0
))

comparison_df = pd.DataFrame(RESULTS)[['model_name', 'precision', 'val_MAE_C', 'val_RMSE_C', 'size_bytes', 'param_count']]
comparison_df_sorted = comparison_df.sort_values('val_RMSE_C').reset_index(drop=True)
comparison_df_sorted.to_csv('model_comparison_v2.csv', index=False)

print("\n" + "=" * 70)
print("FINAL MODEL COMPARISON (sorted by val_RMSE_C ascending)")
print("=" * 70)
print(comparison_df_sorted.to_string(index=False))
print("\nWrote model_comparison_v2.csv")
print("\nHardcode-into-firmware summary:")
print(f"  DT_SECONDS       = {DT_SECONDS}")
print(f"  D_MIN, D_MAX     = {D_MIN}, {D_MAX}")
print(f"  TAU_HAT          = {TAU_HAT}")
print(f"  RESIDUAL_SCALE   = {R_MAX}")
print("\nDone.")
