"""
train_dense_esp32.py
---------------------
Trains a small Dense (MLP) model to correct K-Type thermocouple lag using a
PT100 reference. Dense ops are fully supported by TFLite Micro on ANY ESP32 —
no LSTM kernel required.

WHY NOT LSTM?
  EloquentTinyML v2.x wraps TFLite Micro. The generic ESP32 build of TFLite
  Micro does NOT include the UnidirectionalSequenceLSTM op kernel. That op is
  only available in the ESP32-S3 targeted tflm_esp32s3 package. A Dense model
  with a flat lookback window achieves similar lag-correction results for
  slow thermal signals (2 Hz) and runs on every ESP32 variant.

Model input:  10 consecutive scaled K-Type readings  →  flat float[10]
Model output: 1 scaled corrected temperature value   →  float[1]
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Input, Dense

# --- Configuration ---
CSV_FILE    = 'synthetic_training_data.csv'
HEADER_FILE = 'model_data.h'
LOOKBACK    = 10   # Must match NUMBER_OF_INPUTS in the Arduino sketch

# Normalization bounds — must be identical in the Arduino sketch
T_MIN = 20.0
T_MAX = 80.0

def scale(temp):
    return (temp - T_MIN) / (T_MAX - T_MIN)

def main():
    # 1. Load dataset
    print(f"Loading {CSV_FILE}...")
    df = pd.read_csv(CSV_FILE)

    # 2. Normalize
    k_scaled  = scale(df['K_Type_Temp_C'].values.astype(np.float32))
    pt_scaled = scale(df['PT100_Temp_C'].values.astype(np.float32))

    # 3. Build sliding windows
    # X shape: (samples, LOOKBACK)  — flat, no extra dimension needed for Dense
    # y shape: (samples, 1)
    print("Building sliding windows...")
    X, y = [], []
    for i in range(len(df) - LOOKBACK):
        X.append(k_scaled[i : i + LOOKBACK])
        y.append(pt_scaled[i + LOOKBACK])

    X = np.array(X, dtype=np.float32)          # (N, 10)
    y = np.array(y, dtype=np.float32).reshape(-1, 1)  # (N, 1)

    print(f"  X shape: {X.shape}")
    print(f"  y shape: {y.shape}")

    # 4. Build a tiny Dense model
    #    Two hidden layers — 16 and 8 units — is more than enough for a
    #    smooth thermal lag. Total weights ~250 floats → ~1 KB quantized.
    print("Building Dense model...")
    model = Sequential([
        Input(shape=(LOOKBACK,)),
        Dense(16, activation='relu'),
        Dense(8,  activation='relu'),
        Dense(1)                      # Linear output — regression
    ])

    model.compile(optimizer='adam', loss='mse', metrics=['mae'])
    model.summary()

    # 5. Train
    print("Training...")
    model.fit(
        X, y,
        epochs=20,
        batch_size=64,
        validation_split=0.1,
        verbose=1
    )

    # 6. Convert to TFLite with full integer quantization
    #    DEFAULT optimisation applies dynamic-range quantization:
    #    weights stored as int8, activations computed in float32.
    #    This keeps the model under ~1 KB and speeds up inference on ESP32.
    print("Converting to TFLite...")
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    tflite_model = converter.convert()

    print(f"  TFLite model size: {len(tflite_model)} bytes")

    # 7. Emit C++ header
    print(f"Writing {HEADER_FILE}...")
    hex_parts = []
    for i, byte_val in enumerate(tflite_model):
        if i % 12 == 0:
            hex_parts.append("\n  ")
        hex_parts.append(f"0x{byte_val:02x}, ")

    header = f"""\
// Auto-generated by train_dense_esp32.py — do not edit manually.
// Dense MLP replacing LSTM for ESP32 TFLite Micro compatibility.
#ifndef MODEL_DATA_H
#define MODEL_DATA_H

// 8-byte alignment required by TFLite Micro flatbuffer parser
alignas(8) const unsigned char model_data[] = {{{''.join(hex_parts)}
}};
const unsigned int model_data_len = {len(tflite_model)};

#endif // MODEL_DATA_H
"""
    with open(HEADER_FILE, 'w') as f:
        f.write(header)

    print("Done. Copy model_data.h into your Arduino sketch folder.")

if __name__ == '__main__':
    main()
